### ISSUE TITLE
cannot open the module WiringPiOcaml

### ISSUE THREAD

**Issue by juanbono** [Leonidas-from-XIV/ocaml-wiringpi#2]
Hi! thank you for the bindings!
I was trying to use it on my rapsberry pi (1) model B+ but after the installation process: 
```
oasis setup 
ocaml setup.ml -configure
ocaml setup.ml -build
make 
make install
```
when i try to use the library at the repl
``` ocaml
open WiringPiOcaml;;
```
 it prompts me:
 ```
 Error: Unbound module WiringPiOcaml
```
what can i do?

PS: Information about my setup
 ocaml version : 4.03.0
 wiring pi version: 2.36
 raspberry pi details: Type: Model B+, Revision: 02

**Comment by Leonidas-from-XIV** [comment]
It is best you use the installation via `opam install wiringpi`, this will take care of installing into the right directories and allow uninstallation.

Then you can `#require "WiringPi";;` in the REPL and be able to access all exported functions.

**Comment by juanbono** [comment]
I tried that but i can't load the library if i'm not in the library's directory (~/.opam/4.03.0/lib/WiringPi).

**Comment by juanbono** [comment]
I've added this line to my .ocamlinit file:
```
#use "topfind"
#require "WiringPi"
```
and now it works!
Thank you for your help!
